import VBSBadge from '@/components/application-ui/elements/badge'
import VBSDropdown from '@/components/application-ui/elements/dropdown'
import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VBSDropdown />
    </div>
  )
}
