import VBSDivider from '@/components/application-ui/layout/divider'
import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-20">
        <VBSDivider variant="with-icon" />
      </div>
      <div className="p-20">
        <VBSDivider variant="with-label" label="or" />
      </div>
      <div className="p-20">
        <VBSDivider variant="with-button" buttonText="Button text" />
      </div>
    </div>
  )
}
